force-app/main/default/objects/ContactEncounter/fields/Tracey_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Tracey_Location_Name__c</fullName>
    <formula>IF(ISBLANK(Location.Name), &quot;(none)&quot;,Location.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tracey Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactEncounter/fields/Tracey_StartTime_String__c.field-meta.xml
<CustomField>
    <fullName>Tracey_StartTime_String__c</fullName>
    <formula>TEXT(DATEVALUE(StartTime))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tracey StartTime String</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Tracey_EncounterQuery.cls
global with sharing class Tracey_EncounterQuery 
{
    @InvocableMethod(label='Tracey - Get Contact Encounters')
    global static List<List<ContactEncounter>> getEncounters(List<List<String>> requests) 
    {
        List<List<ContactEncounter>> results = new List<List<ContactEncounter>>();
        List<ContactEncounter> result = new List<ContactEncounter>();
        
        for (List<String> request : requests)
        {
            try
            {
                if (request.size() > 0)
                {
                    result = new List<ContactEncounter>([SELECT Id, Name, StartTime, Description, ActualParticipantCount, EncounterDuration, LocationId, Tracey_Location_Name__c, EstimatedParticipantCount, Tracey_StartTime_String__c  FROM ContactEncounter WHERE ID In: request ORDER BY StartTime DESC]);
                    results.add(result);
                }
            }
            catch(Exception ex)
            {
            }
        }
        return results;
    }
}